### ISSUE TITLE
Will notestar be migrated to quarto?

### ISSUE THREAD

**Issue by rgayler** [tjmahr/notestar#9]
Hi. This is just an idle speculative query.

Given that Rstudio appear to be developing [quarto](https://quarto.org/) as a successor to Rmarkdown I was wondering whether you had any thoughts about migrating notestar to quarto.

notestar is tied to [targets](https://github.com/ropensci/targets), which therefore ties it to the R ecosystem, meaning that the cross-language aspects of quarto are not relevant, but I wouldn't be surprised if at some point Rmarkdown became soft-deprecated relative to quarto.

What do you think?

Thanks & Cheers

**Comment by tjmahr** [comment]
Let me recap how the notestar workflow works:

- We write .Rmd files and create things in _targets.R.
- targets looks for changes in .Rmd files or their dependencies and calls knit::knit() on them to produce .md file
- targets looks for changes in .md files and collates them. It creates or updates an _output.yml file with list of chapter and their collation order. It calls bookdown to assemble the .md files into a single html file.
- the bookdown relies on a really narrow bit of rmarkdown magic. it uses the output format `bookdown::markdown_document2(base_format = "cleanrmd::html_document_clean")` (create a single .md file and run it through cleanrmd.

I would like to keep the first knitting layer in place so that chapters can be conditionally regenerated. 

The bookdown layer could be migrated to quarto in principle. It would require me learning how to make quarto build a single page document (book or report) from a set of md files. Then I would need to figure out how to incorporate styling for the output format.

**Comment by rgayler** [comment]
Thanks!

FWIW there is a post on current plans for quarto development here: [https://github.com/quarto-dev/quarto-cli/discussions/463#discussioncomment-2437882](https://github.com/quarto-dev/quarto-cli/discussions/463#discussioncomment-2437882)

My reading is that switching to quarto would not be imperative in our lifetimes, but it might be attractive if the switching cost was minimal and some of the new quarto features looked useful to you.

**Comment by rgayler** [comment]
Here is an update from the quarto devs. It doesn't answer @tjmahr 's specific dependencies, but it confirms the general intention for Quarto book: [](https://community.rstudio.com/t/bookdown-evolution-in-response-to-quarto/133163/4?u=ross_gayler)
